language: node_js
install:
  - npm install
script:
  - npm run test-travis
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
node_js:
  - "node"
  - "6"
  - "6.9"
  - "6.0"
  - "5"
  - "5.0"
  - "4"
  - "4.0"
  - "iojs"
  